<a href="https://colab.research.google.com/github/Wansh619/GdscPrj1/blob/main/pr1GDSC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Prediction of ex-showroom price from our car_engage dataset**

## **importing important libraries**

In [120]:
import pandas as pd
import numpy as np
import matplotlib as plt

## **uploading data in our variable data**


In [121]:
data=pd.read_csv('cars_engage_2022.csv')


In [122]:
data

Unnamed: 0        Make      Model        Variant Ex-Showroom_Price  \
0              0        Tata  Nano Genx             Xt      Rs. 2,92,667   
1              1        Tata  Nano Genx             Xe      Rs. 2,36,447   
2              2        Tata  Nano Genx        Emax Xm      Rs. 2,96,661   
3              3        Tata  Nano Genx            Xta      Rs. 3,34,768   
4              4        Tata  Nano Genx             Xm      Rs. 2,72,223   
...          ...         ...        ...            ...               ...   
1271        1271       Honda       City   Vx Mt Diesel     Rs. 13,02,000   
1272        1272       Honda       City   Zx Mt Diesel     Rs. 14,21,000   
1273        1273       Honda       City  Zx Cvt Petrol     Rs. 14,31,000   
1274        1274       Honda       City   V Cvt Petrol     Rs. 12,01,000   
1275        1275  Mitsubishi    Montero         3.2 At     Rs. 68,62,560   

     Displacement  Cylinders  Valves_Per_Cylinder               Drivetrain  \
0          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
1          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
2          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
3          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
4          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
...           ...        ...                  ...                      ...   
1271      1498 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1272      1498 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1273      1497 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1274      1497 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1275      3200 cc        4.0                  4.0    AWD (All Wheel Drive)   

     Cylinder_Configuration  ... Leather_Wrapped_Steering Automatic_Headlamps  \
0                   In-line  ...                      NaN                 NaN   
1                   In-line  ...                      NaN                 NaN   
2                   In-line  ...                      NaN                 NaN   
3                   In-line  ...                      NaN                 NaN   
4                   In-line  ...                      NaN                 NaN   
...                     ...  ...                      ...                 ...   
1271                In-line  ...                      Yes                 NaN   
1272                In-line  ...                      Yes                 Yes   
1273                In-line  ...                      Yes                 Yes   
1274                In-line  ...                      NaN                 NaN   
1275                In-line  ...                      Yes                 NaN   

     Engine_Type ASR_/_Traction_Control Cruise_Control USB_Ports  \
0            NaN                    NaN            NaN       NaN   
1            NaN                    NaN            NaN       NaN   
2            NaN                    NaN            NaN       NaN   
3            NaN                    NaN            NaN       NaN   
4            NaN                    NaN            NaN       NaN   
...          ...                    ...            ...       ...   
1271         NaN                    NaN            Yes       NaN   
1272         NaN                    NaN            Yes       NaN   
1273         NaN                    NaN            Yes       NaN   
1274         NaN                    NaN            Yes       NaN   
1275         NaN                    Yes            Yes       NaN   

     Heads-Up_Display Welcome_Lights Battery  Electric_Range  
0                 NaN            NaN     NaN             NaN  
1                 NaN            NaN     NaN             NaN  
2                 NaN            NaN     NaN             NaN  
3                 NaN            NaN     NaN             NaN  
4                 NaN            NaN     NaN       

# **splitting the data into data 2 and 3**

data 3= all the features

In [123]:
data3=data

# **DATA 3**

In [124]:
data3

Unnamed: 0        Make      Model        Variant Ex-Showroom_Price  \
0              0        Tata  Nano Genx             Xt      Rs. 2,92,667   
1              1        Tata  Nano Genx             Xe      Rs. 2,36,447   
2              2        Tata  Nano Genx        Emax Xm      Rs. 2,96,661   
3              3        Tata  Nano Genx            Xta      Rs. 3,34,768   
4              4        Tata  Nano Genx             Xm      Rs. 2,72,223   
...          ...         ...        ...            ...               ...   
1271        1271       Honda       City   Vx Mt Diesel     Rs. 13,02,000   
1272        1272       Honda       City   Zx Mt Diesel     Rs. 14,21,000   
1273        1273       Honda       City  Zx Cvt Petrol     Rs. 14,31,000   
1274        1274       Honda       City   V Cvt Petrol     Rs. 12,01,000   
1275        1275  Mitsubishi    Montero         3.2 At     Rs. 68,62,560   

     Displacement  Cylinders  Valves_Per_Cylinder               Drivetrain  \
0          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
1          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
2          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
3          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
4          624 cc        2.0                  2.0   RWD (Rear Wheel Drive)   
...           ...        ...                  ...                      ...   
1271      1498 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1272      1498 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1273      1497 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1274      1497 cc        4.0                  4.0  FWD (Front Wheel Drive)   
1275      3200 cc        4.0                  4.0    AWD (All Wheel Drive)   

     Cylinder_Configuration  ... Leather_Wrapped_Steering Automatic_Headlamps  \
0                   In-line  ...                      NaN                 NaN   
1                   In-line  ...                      NaN                 NaN   
2                   In-line  ...                      NaN                 NaN   
3                   In-line  ...                      NaN                 NaN   
4                   In-line  ...                      NaN                 NaN   
...                     ...  ...                      ...                 ...   
1271                In-line  ...                      Yes                 NaN   
1272                In-line  ...                      Yes                 Yes   
1273                In-line  ...                      Yes                 Yes   
1274                In-line  ...                      NaN                 NaN   
1275                In-line  ...                      Yes                 NaN   

     Engine_Type ASR_/_Traction_Control Cruise_Control USB_Ports  \
0            NaN                    NaN            NaN       NaN   
1            NaN                    NaN            NaN       NaN   
2            NaN                    NaN            NaN       NaN   
3            NaN                    NaN            NaN       NaN   
4            NaN                    NaN            NaN       NaN   
...          ...                    ...            ...       ...   
1271         NaN                    NaN            Yes       NaN   
1272         NaN                    NaN            Yes       NaN   
1273         NaN                    NaN            Yes       NaN   
1274         NaN                    NaN            Yes       NaN   
1275         NaN                    Yes            Yes       NaN   

     Heads-Up_Display Welcome_Lights Battery  Electric_Range  
0                 NaN            NaN     NaN             NaN  
1                 NaN            NaN     NaN             NaN  
2                 NaN            NaN     NaN             NaN  
3                 NaN            NaN     NaN             NaN  
4                 NaN            NaN     NaN       

# ***putting 'unknown' missing values of catagorical columns ***

### **list of catagorical col label encoded columns and numerical data with units**

In [125]:
 catagory_col=['Make','Drivetrain',
               'Cylinder_Configuration','Emission_Norm',
               'Engine_Location','Fuel_Type','Fuel_System',
               'Body_Type','Front_Brakes','Rear_Brakes','Front_Suspension',
               'Rear_Suspension','Front_Tyre_&_Rim','Rear_Tyre_&_Rim','Power_Steering',
               'Power_Windows','Power_Seats','Keyless_Entry','Power','Torque','Odometer',
               'Speedometer','Tachometer','Tripmeter','Seats_Material','Type','Wheels_Size',
               'Start_/_Stop_Button','12v_Power_Outlet','Audiosystem','Aux-in_Compatibility',
               'Average_Fuel_Consumption','Basic_Warranty','Bluetooth','Boot-lid_Opener','CD_/_MP3_/_DVD_Player',
               'Central_Locking','Child_Safety_Locks','Clock','Cup_Holders','Distance_to_Empty',
               'Door_Pockets','Engine_Malfunction_Light','Extended_Warranty','FM_Radio','Fuel-lid_Opener',
               'Fuel_Gauge','Handbrake','Instrument_Console','Low_Fuel_Warning','Multifunction_Display',
               'Sun_Visor','Third_Row_AC_Vents','Ventilation_System','Drive_Modes',
               'Auto-Dimming_Rear-View_Mirror','Hill_Assist','Gear_Indicator',
               '3_Point_Seat-Belt_in_Middle_Rear_Seat','Ambient_Lightning',
               'Cargo/Boot_Lights','Drive_Modes','Engine_Immobilizer',
               'High_Speed_Alert_System','Lane_Watch_Camera/_Side_Mirror_Camera',
               'Passenger_Side_Seat-Belt_Reminder','Seat_Back_Pockets','Voice_Recognition',
               'Walk_Away_Auto_Car_Lock','ABS_(Anti-lock_Braking_System)','Headlight_Reminder','Adjustable_Headrests',
               'Gross_Vehicle_Weight','Airbags','Door_Ajar_Warning','EBD_(Electronic_Brake-force_Distribution)',
               'Fasten_Seat_Belt_Warning','Gear_Shift_Reminder','Adjustable_Steering_Column','Other_Specs',
               'Parking_Assistance','Key_Off_Reminder','USB_Compatibility','Android_Auto','Apple_CarPlay',
               'Cigarette_Lighter','Infotainment_Screen','Multifunction_Steering_Wheel','Average_Speed',
               'EBA_(Electronic_Brake_Assist)','Seat_Height_Adjustment','Navigation_System','Second_Row_AC_Vents',
               'Tyre_Pressure_Monitoring_System','Rear_Center_Armrest','iPod_Compatibility','ESP_(Electronic_Stability_Program)',
               'Cooled_Glove_Box','Heated_Seats','Turbocharger','ISOFIX_(Child-Seat_Mount)','Rain_Sensing_Wipers',
               'Paddle_Shifters','Leather_Wrapped_Steering','Automatic_Headlamps','Engine_Type','ASR_/_Traction_Control',
               'Cruise_Control','Heads-Up_Display','Welcome_Lights'
               ] 


In [126]:
dimention={           
        'mm_unit':  ['Height','Length',
                    'Width','Ground_Clearance',
                    'Front_Track','Rear_Track','Wheelbase'
                    ],
           
        'litre_unit': ['Fuel_Tank_Capacity','Boot_Space'],
        
        'km_per_litre':['City_Mileage','Highway_Mileage','ARAI_Certified_Mileage'],

        'kilogram':['Kerb_Weight','Gross_Vehicle_Weight'],

        'dim_less':['Gears','Compression_Ratio','USB_Ports']
}


In [127]:

labelE=['Tripmeter','Start_/_Stop_Button','12v_Power_Outlet',
        'Aux-in_Compatibility','Average_Fuel_Consumption',
        'Bluetooth','CD_/_MP3_/_DVD_Player','Central_Locking',
        'Child_Safety_Locks','Distance_to_Empty','Engine_Malfunction_Light',
        'FM_Radio','Low_Fuel_Warning','Multifunction_Display',
        'Auto-Dimming_Rear-View_Mirror','Hill_Assist','Gear_Indicator',
        '3_Point_Seat-Belt_in_Middle_Rear_Seat','Ambient_Lightning','Cargo/Boot_Lights',
        'Engine_Immobilizer','High_Speed_Alert_System','Lane_Watch_Camera/_Side_Mirror_Camera',
        'Passenger_Side_Seat-Belt_Reminder','Seat_Back_Pockets','Voice_Recognition',
        'Walk_Away_Auto_Car_Lock','ABS_(Anti-lock_Braking_System)','Headlight_Reminder',
        'Door_Ajar_Warning','EBD_(Electronic_Brake-force_Distribution)','Fasten_Seat_Belt_Warning',
        'Gear_Shift_Reminder','Key_Off_Reminder','USB_Compatibility','Android_Auto','Apple_CarPlay',
        'Cigarette_Lighter','Average_Speed','EBA_(Electronic_Brake_Assist)','Navigation_System','Second_Row_AC_Vents',
        'Tyre_Pressure_Monitoring_System','iPod_Compatibility','ESP_(Electronic_Stability_Program)','Cooled_Glove_Box',
        'Turbocharger','ISOFIX_(Child-Seat_Mount)','Rain_Sensing_Wipers','Paddle_Shifters',
        'Leather_Wrapped_Steering','Automatic_Headlamps','ASR_/_Traction_Control','Cruise_Control',
        'Heads-Up_Display','Welcome_Lights','Power_Seats','Keyless_Entry'
        ]

In [128]:

mean_data=['Cylinders','Valves_Per_Cylinder','Fuel_Tank_Capacity',
'Height','Width','City_Mileage',
'Highway_Mileage','ARAI_Certified_Mileage','ARAI_Certified_Mileage_for_CNG',
'Kerb_Weight','Gears','Ground_Clearance',
'Front_Track','Rear_Track','Wheelbase',
'Boot_Space','Minimum_Turning_Radius','Gross_Vehicle_Weight',
'Compression_Ratio','USB_Ports','Battery',
'Electric_Range','Ex-Showroom_Price','Displacement'
]

In [129]:
median_data=['Cylinders','Doors',
            'Seating_Capacity','Number_of_Airbags'
            ]

filling the missing values in dataset

In [130]:
for col in catagory_col:
  data3[col]=data3[col].fillna('unknown')

# **conversion of numerical data from string to integer**

removing all units to form int 

In [131]:
# for data 3 

for col in dimention['mm_unit']:
  data3[col]=data3[col].str.replace("mm","")
  data3[col]=pd.to_numeric(data3[col],errors='coerce')


for col in dimention['litre_unit']:
  data3[col]=data3[col].str.replace("litres","")
  data3[col]=pd.to_numeric(data3[col],errors='coerce')

for col in dimention['km_per_litre']:
  data3[col]=data3[col].str.replace("km/litre","")
  data3[col]=pd.to_numeric(data3[col],errors='coerce')

for col in dimention['kilogram']:
  data3[col]=data3[col].str.replace("kg","")
  data3[col]=pd.to_numeric(data3[col],errors='coerce')

for col in dimention['dim_less']:
  data3[col]=pd.to_numeric(data3[col],errors='coerce')

 #special cases
data3['Displacement']=data3['Displacement'].str.replace("cc","")
data3['Displacement']=pd.to_numeric(data3['Displacement'],errors='coerce')

data3['ARAI_Certified_Mileage_for_CNG']=data3['ARAI_Certified_Mileage_for_CNG'].str.replace("km/kg","")
data3['ARAI_Certified_Mileage_for_CNG']=pd.to_numeric(data3['ARAI_Certified_Mileage_for_CNG'],errors='coerce')

data3['Minimum_Turning_Radius']=data3['Minimum_Turning_Radius'].str.replace("meter","")
data3['Minimum_Turning_Radius']=pd.to_numeric(data3['Minimum_Turning_Radius'],errors='coerce')

data3['Electric_Range']=data3['Electric_Range'].str.replace("km/full charge","")
data3['Electric_Range']=pd.to_numeric(data3['Electric_Range'],errors='coerce')

data3['Battery']=data3['Battery'].str.replace("ampere-hour","").str.replace("kWh,Battery Placed Under Rear Seats","").str.replace("(kWh), Lithium Ion","").str.replace(" kWh* Advanced Li-ion polymer, liquid cooled battery pack with IP67 certification","").str.replace("","").str.replace("(kWh), Lithium Ion","")
data3['Battery']=pd.to_numeric(data3['Battery'],errors='coerce')

#for data 2 removing units
data3['Ex-Showroom_Price']=data3['Ex-Showroom_Price'].str.replace("Rs.","").str.replace(",","")
data3['Ex-Showroom_Price']=pd.to_numeric(data3['Ex-Showroom_Price'],errors='coerce')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:36: FutureWarning: The default value of regex will change from True to False in a future version.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:40: FutureWarning: The default value of regex will change from True to False in a future version.


filling missing values with mean and median

In [132]:
# for data 3 converting to mean

for col in mean_data:
  data3[col]=data[col].fillna(data3[col].mean())

for col in median_data:
  data3[col]=data3[col].fillna(data3[col].median())

# **DATA 2**


this data consist of the features (ex-showroom price)

In [133]:
data2=data3.pop('Ex-Showroom_Price')

## **one hot encoding on data frame**

In [134]:
data3 = pd.get_dummies(data3, columns = ['Make','Model','Variant','Drivetrain','Cylinder_Configuration','Emission_Norm','Engine_Location','Fuel_System','Fuel_Type','Body_Type','Front_Brakes','Rear_Brakes','Front_Suspension','Rear_Suspension','Front_Tyre_&_Rim','Rear_Tyre_&_Rim','Power_Steering','Power_Windows','Power','Torque','Odometer','Speedometer','Tachometer','Seats_Material','Type','Wheels_Size','Audiosystem','Basic_Warranty','Boot-lid_Opener','Clock','Cup_Holders','Door_Pockets','Extended_Warranty','Fuel-lid_Opener','Fuel_Gauge','Handbrake','Instrument_Console','Sun_Visor','Third_Row_AC_Vents','Ventilation_System','Adjustable_Headrests','Airbags','Adjustable_Steering_Column','Other_Specs','Other_specs','Parking_Assistance','Infotainment_Screen','Multifunction_Steering_Wheel','Seat_Height_Adjustment','Rear_Center_Armrest','Recommended_Tyre_Pressure','Heated_Seats','Engine_Type','Drive_Modes']) 

label encoding

In [135]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for col in labelE:
  data3[col]=le.fit_transform(data3[col])

importing ML models

In [136]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR

from sklearn.ensemble import RandomForestRegressor

In [137]:
x=np.array(data3)
y=np.array(data2)

# **splitting into training and test set**

In [138]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=0)

# calculate r^2
from sklearn.metrics import r2_score

# **fitting all models with the data**

LINEAR REGRESSION MODEL

In [139]:

lr=LinearRegression()

lr.fit(x_train,y_train)

LinearRegression()

DECISON TREE

In [140]:
from sklearn.tree import DecisionTreeRegressor
dt=DecisionTreeRegressor()
dt.fit(x_train,y_train)


DecisionTreeRegressor()

RANDOM FOREST REGRESSION

In [141]:
rfr=RandomForestRegressor(n_estimators= 15, random_state=0)
rfr.fit(x_train,y_train)


RandomForestRegressor(n_estimators=15, random_state=0)

# **visualisation of results bu ML models**

for linear regression model


In [142]:
print(lr.predict(x_test))

[ 1.05597620e+06  6.48730663e+05  1.04212814e+07  7.70418105e+05
  1.51873815e+06  7.30480181e+05  4.13264044e+07  1.86448860e+06
  8.39527484e+05  1.23184447e+06  1.86786715e+06  2.87071439e+06
  3.35137700e+06  1.45174516e+06  9.79276711e+05  2.48805432e+05
  3.48624649e+06 -4.23881079e+05  7.28937855e+06  1.13132860e+06
  2.64893317e+06  1.87710632e+06  2.33292006e+07 -1.93824338e+06
 -2.83447432e+06  7.19875589e+05  4.00436908e+06  5.85965940e+04
  2.32337325e+06  9.75808290e+05  1.10321285e+07  1.46450106e+06
  4.58714609e+05  2.38570194e+05  1.41258400e+07  1.41831300e+06
  4.84930795e+07  1.32899569e+06  1.10133639e+05  1.47521063e+06
  3.08777478e+06  1.20047939e+06  3.02704763e+05  4.88708447e+05
  3.26190984e+06  5.24865101e+05  5.66856176e+05  2.41799291e+06
  7.36094022e+05  9.51353905e+05  6.34649425e+05  2.23290411e+06
  3.12467185e+06 -1.18139981e+06  5.54056470e+04  2.02703208e+06
  2.21248597e+07  8.28761197e+05 -1.32327540e+05 -3.01957345e+05
  2.67606977e+06  7.46096

In [143]:
print(y_test)

[  1610000    999900   8690000    699400    697400    520000  32200000
   1944900    405570    599000    862175   1728000   1336033    823700
    808558    314815   3019000    570990   3470000   1629000   2779599
    773678  29500000   1328000    480670    360843   3990000    513501
    664900   1394437   8670586    983000    904000    863122  11476911
   1418313  24250000    463290    796132    737400   1095000   3564000
    914328    352900   2599599    812964    732475    989219    816000
    876000   1900000   1210500   3099599    781000    620637    674960
  21875136   1059742    788797   1069689   2199000   8470000   1138189
    821613   1634000   1354000   2167000  35535000    236447    942867
    689600    860997    573250   1111000    942263   1317000   1348000
    734700    469990    794800    773800    739000    732113    519000
   2070000   2187384    999900   7693664    988500   9665000    940500
    854900    383290   1279983   1465000   4240000    684000    769000
    50

In [144]:
r2_score(y_test,lr.predict(x_test))

0.8799012235104116

support vector regression model

In [145]:
sr=SVR(kernel='rbf')
sr.fit(x_train,y_train)


SVR()

In [146]:
sr.predict(x_test)


array([1089037.00544867, 1089011.13767276, 1089057.23159031,
       1089000.01256827, 1088994.81568348, 1088986.82187039,
       1089069.87794784, 1089016.25469747, 1088972.76701684,
       1088987.89323867, 1089001.23638213, 1089022.64555079,
       1089010.3699935 , 1088994.24381158, 1089005.23028341,
       1088970.35147557, 1089046.39437821, 1088987.58260018,
       1089054.46799981, 1089006.21005134, 1089023.1045116 ,
       1089029.38072335, 1089056.70265553, 1089013.68322705,
       1088979.44664802, 1088975.06677783, 1089015.47474218,
       1088987.59017592, 1088994.72132964, 1089007.65649585,
       1089039.37318561, 1088999.99227579, 1089001.27716903,
       1088988.8138901 , 1089057.95956433, 1089030.79342729,
       1089088.34408155, 1088981.66671145, 1088994.55104663,
       1088994.85189164, 1089010.98393199, 1089025.40947376,
       1089009.17558424, 1088972.75396855, 1089022.1737409 ,
       1088994.92927035, 1088991.19440205, 1088999.94567379,
       1088993.33878875,

In [147]:
y_test

array([  1610000,    999900,   8690000,    699400,    697400,    520000,
        32200000,   1944900,    405570,    599000,    862175,   1728000,
         1336033,    823700,    808558,    314815,   3019000,    570990,
         3470000,   1629000,   2779599,    773678,  29500000,   1328000,
          480670,    360843,   3990000,    513501,    664900,   1394437,
         8670586,    983000,    904000,    863122,  11476911,   1418313,
        24250000,    463290,    796132,    737400,   1095000,   3564000,
          914328,    352900,   2599599,    812964,    732475,    989219,
          816000,    876000,   1900000,   1210500,   3099599,    781000,
          620637,    674960,  21875136,   1059742,    788797,   1069689,
         2199000,   8470000,   1138189,    821613,   1634000,   1354000,
         2167000,  35535000,    236447,    942867,    689600,    860997,
          573250,   1111000,    942263,   1317000,   1348000,    734700,
          469990,    794800,    773800,    739000, 

In [148]:
r2_score(y_test,sr.predict(x_test))

-0.0662712196872739

decision tree model

In [149]:
dt.predict(x_test)

array([1.58700000e+06, 9.99900000e+05, 8.77690000e+06, 6.66622000e+05,
       8.10211000e+05, 5.70000000e+05, 4.07429320e+07, 4.14000000e+06,
       4.09190000e+05, 7.11801000e+05, 7.15860000e+05, 8.35275000e+05,
       1.19791900e+06, 7.28900000e+05, 7.78400000e+05, 2.72223000e+05,
       3.21600000e+06, 5.78990000e+05, 1.11412000e+07, 1.62900000e+06,
       5.89000000e+06, 8.15883000e+05, 2.12402720e+07, 1.49800000e+06,
       4.81074000e+05, 3.92967000e+05, 2.69300000e+06, 5.20500000e+05,
       7.18950000e+05, 1.42293700e+06, 9.44818100e+06, 9.59000000e+05,
       9.29000000e+05, 7.79113000e+05, 1.32287250e+07, 1.41831300e+06,
       5.32472010e+07, 4.84490000e+05, 7.45900000e+05, 7.58314000e+05,
       1.46500000e+06, 3.86400000e+06, 9.76592000e+05, 3.57200000e+05,
       5.89000000e+06, 7.20700000e+05, 7.51693000e+05, 7.85000000e+05,
       7.66000000e+05, 9.35000000e+05, 1.99600000e+06, 9.99900000e+05,
       3.02120000e+06, 8.77300000e+05, 6.40537000e+05, 7.87980000e+05,
      

In [150]:
y_test

array([  1610000,    999900,   8690000,    699400,    697400,    520000,
        32200000,   1944900,    405570,    599000,    862175,   1728000,
         1336033,    823700,    808558,    314815,   3019000,    570990,
         3470000,   1629000,   2779599,    773678,  29500000,   1328000,
          480670,    360843,   3990000,    513501,    664900,   1394437,
         8670586,    983000,    904000,    863122,  11476911,   1418313,
        24250000,    463290,    796132,    737400,   1095000,   3564000,
          914328,    352900,   2599599,    812964,    732475,    989219,
          816000,    876000,   1900000,   1210500,   3099599,    781000,
          620637,    674960,  21875136,   1059742,    788797,   1069689,
         2199000,   8470000,   1138189,    821613,   1634000,   1354000,
         2167000,  35535000,    236447,    942867,    689600,    860997,
          573250,   1111000,    942263,   1317000,   1348000,    734700,
          469990,    794800,    773800,    739000, 

In [151]:
r2_score(y_test,dt.predict(x_test))

0.9583349824072571

Random forest regression model

In [152]:
rfr.predict(x_test)

array([1.61453333e+06, 1.10908207e+06, 9.06148160e+06, 7.50348067e+05,
       7.70899933e+05, 5.97406200e+05, 3.98263768e+07, 2.52630560e+06,
       3.75357733e+05, 6.68438533e+05, 1.05334700e+06, 3.35303933e+06,
       1.22432680e+06, 7.01986067e+05, 8.97660267e+05, 2.93472667e+05,
       2.97719380e+06, 5.65723733e+05, 9.75878760e+06, 1.55719333e+06,
       3.31921940e+06, 8.57397000e+05, 3.02154106e+07, 1.53215120e+06,
       5.29847933e+05, 4.19739867e+05, 3.64829053e+06, 5.54645733e+05,
       7.36384200e+05, 1.37925473e+06, 1.12804152e+07, 9.77111133e+05,
       9.53179267e+05, 8.69113867e+05, 1.40032709e+07, 1.88486793e+06,
       6.00522517e+07, 4.85535200e+05, 7.15149133e+05, 8.05458867e+05,
       1.34189913e+06, 3.89470300e+06, 9.56547867e+05, 3.67034267e+05,
       2.98961627e+06, 8.72466733e+05, 8.38956267e+05, 8.83833067e+05,
       7.69175067e+05, 9.58191133e+05, 2.12508667e+06, 1.11276593e+06,
       3.09469360e+06, 8.38481133e+05, 6.24076467e+05, 7.74752933e+05,
      

In [153]:
y_test

array([  1610000,    999900,   8690000,    699400,    697400,    520000,
        32200000,   1944900,    405570,    599000,    862175,   1728000,
         1336033,    823700,    808558,    314815,   3019000,    570990,
         3470000,   1629000,   2779599,    773678,  29500000,   1328000,
          480670,    360843,   3990000,    513501,    664900,   1394437,
         8670586,    983000,    904000,    863122,  11476911,   1418313,
        24250000,    463290,    796132,    737400,   1095000,   3564000,
          914328,    352900,   2599599,    812964,    732475,    989219,
          816000,    876000,   1900000,   1210500,   3099599,    781000,
          620637,    674960,  21875136,   1059742,    788797,   1069689,
         2199000,   8470000,   1138189,    821613,   1634000,   1354000,
         2167000,  35535000,    236447,    942867,    689600,    860997,
          573250,   1111000,    942263,   1317000,   1348000,    734700,
          469990,    794800,    773800,    739000, 

In [154]:
r2_score(y_test,rfr.predict(x_test))

0.8916809076129472

POLYNOMIAL REGRESSION

In [155]:
from sklearn.preprocessing import PolynomialFeatures

In [ ]:
pf=PolynomialFeatures(degree=2)
x_poly=pf.fit_transform(x_test)